const HABITS=[['reading','📚','Baca — maksimal 15 menit',20],['training','🏋️','Latihan / bergerak',25],['building','💻','Bangun sesuatu yang berguna',20],['finance','💰','Catat / jaga keuangan',10],['reflection','🧠','Refleksi diri',10],['sleep','😴','Jaga waktu tidur',15]];
const KEY='personalGrowthData';
const data=JSON.parse(localStorage.getItem(KEY)||'{"days":{},"journals":{}}');
const start=new Date('2026-09-26T00:00:00');const checkpoint=new Date('2027-03-26T00:00:00');const end=new Date('2031-09-26T00:00:00');const now=new Date();
const todayKey=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);const day=Math.max(1,Math.floor((now-start)/86400000)+1);const $=id=>document.getElementById(id);
$('today').textContent=now.toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase();$('dayCount').textContent=day;$('journeyLabel').textContent=`Hari ${day}`;
const sixPct=Math.max(0,Math.min(100,((now-start)/(checkpoint-start))*100));const fivePct=Math.max(0,Math.min(100,((now-start)/(end-start))*100));$('sixMonthBar').style.width=sixPct+'%';$('fiveYearBar').style.width=fivePct+'%';
function allXp(){return Object.values(data.days).reduce((sum,d)=>sum+HABITS.reduce((s,h)=>s+(d[h[0]]?h[3]:0),0),0)}
function getStreak(){let n=0,d=new Date(now);while(true){const k=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);const checks=data.days[k]||{};if(!HABITS.some(h=>checks[h[0]]))break;n++;d.setDate(d.getDate()-1);if(n>1825)break}return n}
function render(){const checks=data.days[todayKey]||{};$('habits').innerHTML='';HABITS.forEach(([id,icon,label,xp])=>{const el=document.createElement('div');el.className='habit '+(checks[id]?'done':'');el.innerHTML=`<div><span class="quest-icon">${icon}</span><span>${label}</span></div><b>+${xp} EXP</b><span class="check"></span>`;el.onclick=()=>{data.days[todayKey]??={};data.days[todayKey][id]=!data.days[todayKey][id];save()};$('habits').appendChild(el)});
const done=HABITS.filter(h=>checks[h[0]]).length;const pct=Math.round(done/HABITS.length*100);const xp=allXp();const level=Math.floor(xp/100)+1;const inLevel=xp%100;$('progressText').textContent=pct+'%';$('progressBar').style.width=pct+'%';$('totalXp').textContent=xp;$('xpText').textContent=`${inLevel} / 100`;$('xpBar').style.width=inLevel+'%';$('level').textContent=level;$('rank').textContent=level>=20?'PEMAIN S':level>=10?'PEMAIN A':level>=5?'PEMAIN C':'PEMAIN E';
const checkins=Object.keys(data.days).filter(k=>Object.values(data.days[k]||{}).some(Boolean)).length;$('checkinCount').textContent=checkins;$('journalCount').textContent=Object.keys(data.journals).length;$('consistency').textContent=Math.min(100,Math.round(checkins/Math.max(1,day)*100))+'%';$('discipline').textContent=checkins;$('streak').textContent=getStreak();renderHistory()}
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function loadJournal(){const j=data.journals[todayKey]||{};['did','learned','wrong','tomorrow'].forEach(id=>$(id).value=j[id]||'')}
function renderHistory(){const entries=Object.keys(data.journals).sort().reverse();$('logCount').textContent=`${entries.length} ${entries.length===1?'entri':'entri'}`;const box=$('history');box.innerHTML='';if(!entries.length){box.innerHTML='<div class="empty">Jurnal pertamamu akan muncul di sini.</div>';return}entries.slice(0,10).forEach(k=>{const j=data.journals[k];const item=document.createElement('article');item.className='history-item';item.innerHTML=`<div><b>${new Date(k+'T00:00:00').toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase()}</b><span>${j.did||'Tidak ada catatan aktivitas.'}</span></div><button data-date="${k}">Buka</button>`;item.querySelector('button').onclick=()=>loadEntry(k);box.appendChild(item)})}
function loadEntry(k){const j=data.journals[k]||{};['did','learned','wrong','tomorrow'].forEach(id=>$(id).value=j[id]||'');$('saveStatus').textContent=`Melihat ${k}`;window.scrollTo({top:$('did').getBoundingClientRect().top+window.scrollY-100,behavior:'smooth'})}
$('saveJournal').onclick=()=>{data.journals[todayKey]={did:$('did').value.trim(),learned:$('learned').value.trim(),wrong:$('wrong').value.trim(),tomorrow:$('tomorrow').value.trim()};save();$('saveStatus').textContent='Jurnal tersimpan · '+new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'});setTimeout(()=>$('saveStatus').textContent='',2500)};
$('clearJournal').onclick=()=>{['did','learned','wrong','tomorrow'].forEach(id=>$(id).value='');$('saveStatus').textContent='Form dibersihkan'};loadJournal();render();
